version: '3'

services:
  db:
    image: postgres
  web:
    build: ./mysite/
    command: ["./wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./mysite:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
